steps:
  # 1) Installer toutes les dépendances et lancer les tests
  - name: "node:18-slim"
    entrypoint: "bash"
    args:
      - -c
      - |
        echo "Installing all dependencies..."
        npm install
        echo "Running tests..."
        npm test

  # 2) Construire l'image Docker
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "europe-west1-docker.pkg.dev/$PROJECT_ID/hello-app/hello-app:latest",
        "."
      ]

  # 3) Pousser l'image Docker vers le registre
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "europe-west1-docker.pkg.dev/$PROJECT_ID/hello-app/hello-app:latest"
      ]

  # 4) Déployer sur Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "hello-app",
        "--image",
        "europe-west1-docker.pkg.dev/$PROJECT_ID/hello-app/hello-app:latest",
        "--region",
        "europe-west1",
        "--platform",
        "managed",
        "--allow-unauthenticated"
      ]

# Image finale à stocker
images:
  - "europe-west1-docker.pkg.dev/$PROJECT_ID/hello-app/hello-app:latest"

# Compte de service utilisé pour déploiement Cloud Run
serviceAccount: "cloud-run-deployer@ci-cd-cloudrun.iam.gserviceaccount.com"

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: "E2_HIGHCPU_8"
timeout: "1200s"
