timeout: "1200s"

substitutions:
  _SERVICE_NAME: "hello-app"
  _REGION: "europe-west1"
  _TAG: "latest"

steps:

  # 1) Construction de l'image Docker
  - name: "gcr.io/cloud-builders/docker"
    id: "Build Image"
    args: [
      "build",
      "-t", "europe-west1-docker.pkg.dev/$PROJECT_ID/${_SERVICE_NAME}/${_SERVICE_NAME}:${_TAG}",
      "."
    ]

  # 2) Push vers Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    id: "Push Image"
    waitFor: ["Build Image"]
    args: [
      "push",
      "europe-west1-docker.pkg.dev/$PROJECT_ID/${_SERVICE_NAME}/${_SERVICE_NAME}:${_TAG}"
    ]

  # 3) Sauvegarde dernière révision stable
  - name: "google/cloud-sdk"
    id: "Save Old Revision"
    waitFor: ["Push Image"]
    entrypoint: "bash"
    args:
      - -c
      - |
        REV=$$(gcloud run services describe ${_SERVICE_NAME} \
          --region ${_REGION} \
          --platform managed \
          --format='value(status.latestReadyRevisionName)' 2>/dev/null)

        echo $$REV > /workspace/old_revision.txt
        echo "Ancienne révision sauvegardée: $$REV"

  # 4) Déploiement sur Cloud Run
  - name: "google/cloud-sdk"
    id: "Deploy Cloud Run"
    waitFor: ["Save Old Revision"]
    entrypoint: "gcloud"
    args: [
      "run", "deploy", "${_SERVICE_NAME}",
      "--image", "europe-west1-docker.pkg.dev/$PROJECT_ID/${_SERVICE_NAME}/${_SERVICE_NAME}:${_TAG}",
      "--region", "${_REGION}",
      "--platform", "managed",
      "--allow-unauthenticated"
    ]

  # 5) Smoke Test + Rollback
  - name: "google/cloud-sdk"
    id: "Smoke Test & Rollback"
    waitFor: ["Deploy Cloud Run"]
    entrypoint: "bash"
    args:
      - -c
      - |
        SERVICE="${_SERVICE_NAME}"
        REGION="${_REGION}"
        OLD_REV=$$(cat /workspace/old_revision.txt)

        echo "Smoke Test en cours…"
        URL=$$(gcloud run services describe $$SERVICE --region $$REGION --format='value(status.url)')
        echo "Test URL: $$URL/health"

        OK=0
        for i in 1 2 3 4 5; do
          STATUS=$$(curl -s -o /dev/null -w "%{http_code}" "$$URL/health")
          echo "Tentative $$i → $$STATUS"
          if [ "$$STATUS" -ge 200 ] && [ "$$STATUS" -lt 300 ]; then
            OK=1
            break
          fi
          sleep 3
        done
        
        if [ "$$OK" -ne 1 ]; then
         echo "❌ Smoke test échoué — rollback…"

         BAD_REV=$$(gcloud run services describe $$SERVICE \
           --region $$REGION \
           --format='value(status.latestCreatedRevisionName)')

         if [ -n "$$OLD_REV" ] && [ "$$OLD_REV" != "NONE" ]; then
           echo "Rollback vers $$OLD_REV"

           gcloud run services update-traffic $$SERVICE \
             --region $$REGION \
             --to-revisions "$$OLD_REV=100"

           echo " Rollback effectué."

           # 🗑 Suppression sécurisée de la révision défectueuse
           if [ -n "$$BAD_REV" ] && [ "$$BAD_REV" != "$$OLD_REV" ]; then
             echo "🗑 Suppression de la révision défectueuse : $$BAD_REV"
             gcloud run revisions delete "$$BAD_REV" \
               --region "$$REGION" \
               --quiet || echo "⚠ Impossible de supprimer $$BAD_REV car c'est la dernière révision crée."
           fi

         else
           echo "Pas de révision précédente → rollback impossible"
         fi
         exit 1
        fi
images:
  - "europe-west1-docker.pkg.dev/$PROJECT_ID/${_SERVICE_NAME}/${_SERVICE_NAME}:${_TAG}"

serviceAccount: "cloud-run-deployer@ci-cd-cloudrun.iam.gserviceaccount.com"

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: "E2_HIGHCPU_8"
