# Fichier Cloud Build (cloudbuild.yaml)
# Déploiement CI/CD sur Cloud Run avec Smoke Test et Rollback.
#
# Les options machineType et timeout sont à la racine (CORRIGÉ).

timeout: "1200s"
machineType: "E2_HIGHCPU_8"

steps:
  # 1) Construction de l'Image Docker
  - name: "gcr.io/cloud-builders/docker"
    args: [
      "build",
      "-t",
      "europe-west1-docker.pkg.dev/$PROJECT_ID/hello-app/hello-app:latest",
      "."
    ]
    id: 'Construction Image Docker'

  # 2) Push de l'Image vers Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args: [
      "push",
      "europe-west1-docker.pkg.dev/$PROJECT_ID/hello-app/hello-app:latest"
    ]
    id: 'Pousser Image'
    waitFor: ['Construction Image Docker']

  # 3) Déploiement sur Cloud Run (Nouvelle révision mise en ligne)
  - name: "gcr.io/cloud-builders/gcloud"
    args: [
      "run",
      "deploy",
      "hello-app",
      "--image",
      "europe-west1-docker.pkg.dev/$PROJECT_ID/hello-app/hello-app:latest",
      "--region",
      "europe-west1",
      "--platform",
      "managed",
      "--allow-unauthenticated",
      "--set-env-vars",
      "BUILD_ID=$BUILD_ID"
    ]
    id: 'Déploiement Cloud Run'
    waitFor: ['Pousser Image']

  # 4) Smoke Test (Vérification de la santé du déploiement)
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - -c
      - |
        echo "Running smoke test..."
        SERVICE_NAME="hello-app"
        REGION="europe-west1"
        
        URL=$$(gcloud run services describe $$SERVICE_NAME --region $$REGION --format='value(status.url)')
        STATUS=$$(curl -s -o /dev/null -w "%{http_code}" $$URL/health)

        echo "Smoke test status: $$STATUS"

        if [ "$$STATUS" -ne 200 ]; then
          echo "❌ Smoke test failed! Forcing échec pour signal de rollback..."
          exit 1
        fi

        echo "✅ Smoke test passed!"
    id: 'Smoke Test'
    waitFor: ['Déploiement Cloud Run']
    allowFailure: true # PERMET À L'ÉTAPE 5 DE S'EXÉCUTER MÊME EN CAS D'ÉCHEC

  # 5) Rollback (Exécuté après le Smoke Test, qu'il ait réussi ou échoué)
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - -c
      - |
        # Pour une logique de rollback conditionnel, nous vérifions si l'étape précédente a échoué.
        # En l'absence de variable d'état simple, nous faisons un rollback simple si le build global échoue.
        
        # Si le Smoke Test a échoué (exit 1), cette étape est lancée pour annuler le déploiement.
        echo "Lancement du Rollback vers la version précédente..."
        SERVICE_NAME="hello-app"
        REGION="europe-west1"

        # Commande pour allouer 100% du trafic à la révision précédente (la dernière connue pour fonctionner)
        gcloud run services update $$SERVICE_NAME \
          --region $$REGION \
          --to-previous \
          --platform managed
        
        echo "✅ Rollback terminé."
    id: 'Rollback'
    waitFor: ['Smoke Test']


# Déclaration des images produites pour l'historique
images:
  - "europe-west1-docker.pkg.dev/$PROJECT_ID/hello-app/hello-app:latest"

# Configuration des permissions
serviceAccount: "cloud-run-deployer@ci-cd-cloudrun.iam.gserviceaccount.com"

options:
  logging: CLOUD_LOGGING_ONLY