timeout: "1200s" # À la racine, supporté par la plupart des versions.

steps:
  # 1) Construction de l'Image Docker
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "europe-west1-docker.pkg.dev/$PROJECT_ID/hello-app/hello-app:latest", "."]
    id: 'Construction Image Docker'

  # 2) Push de l'Image vers Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "europe-west1-docker.pkg.dev/$PROJECT_ID/hello-app/hello-app:latest"]
    id: 'Pousser Image'
    waitFor: ['Construction Image Docker']

  # 3) Sauvegarder l'ID de la révision stable actuelle
  - name: "google/cloud-sdk"
    entrypoint: "bash"
    args:
      - -c
      - |
        # Récupère le nom de la dernière révision qui était stable (prête)
        OLD_REVISION=$$(gcloud run services describe hello-app \
          --region europe-west1 \
          --platform managed \
          --format='value(status.latestReadyRevisionName)' 2>/dev/null)
        
        # Stocker la révision dans un fichier de l'espace de travail
        echo $$OLD_REVISION > /workspace/old_revision.txt
        echo "Ancienne révision stockée pour rollback: $$OLD_REVISION"
    id: 'Sauvegarde Révision'
    waitFor: ['Pousser Image']

  # 4) Déploiement sur Cloud Run (CORRIGÉ : Ajout de entrypoint: "gcloud")
  - name: "google/cloud-sdk"
    entrypoint: "gcloud" # <-- CORRECTION APPLIQUÉE
    args: [
      "run",
      "deploy",
      "hello-app",
      "--image",
      "europe-west1-docker.pkg.dev/$PROJECT_ID/hello-app/hello-app:latest",
      "--region",
      "europe-west1",
      "--platform",
      "managed",
      "--allow-unauthenticated",
      "--set-env-vars", "BUILD_ID=$BUILD_ID"
    ]
    id: 'Déploiement Cloud Run'
    waitFor: ['Sauvegarde Révision']

  # 5) Smoke Test & Rollback Intégré
  - name: "google/cloud-sdk"
    entrypoint: "bash"
    args:
      - -c
      - |
        echo "Running smoke test and conditional rollback..."
        SERVICE_NAME="hello-app"
        REGION="europe-west1"
        OLD_REVISION=$$(cat /workspace/old_revision.txt)
        
        URL=$$(gcloud run services describe $$SERVICE_NAME --region $$REGION --format='value(status.url)')
        STATUS=$$(curl -s -o /dev/null -w "%{http_code}" $$URL/health)

        echo "Smoke test status: $$STATUS"

        if [ "$$STATUS" -ne 200 ]; then
          echo "❌ Smoke test failed! HTTP Status code $$STATUS. Initiating Rollback to $$OLD_REVISION..."
        
          # COMMANDE DE ROLLBACK CORRIGÉE pour SDK moderne
          gcloud run services update $$SERVICE_NAME \
            --region $$REGION \
            --platform managed \
            --traffic $$OLD_REVISION=100
        
          echo "✅ Rollback terminé. Le build va maintenant échouer."
          exit 1
        fi

        echo "✅ Smoke test passed! Deployment complete."
    id: 'Smoke Test & Rollback'
    waitFor: ['Déploiement Cloud Run']

images:
  - "europe-west1-docker.pkg.dev/$PROJECT_ID/hello-app/hello-app:latest"

serviceAccount: "cloud-run-deployer@ci-cd-cloudrun.iam.gserviceaccount.com"

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: "E2_HIGHCPU_8"