timeout: "1200s"

steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "europe-west1-docker.pkg.dev/$PROJECT_ID/hello-app/hello-app:latest", "."]
    id: "Construction Image Docker"

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "europe-west1-docker.pkg.dev/$PROJECT_ID/hello-app/hello-app:latest"]
    id: "Pousser Image"
    waitFor: ["Construction Image Docker"]

  - name: "google/cloud-sdk"
    entrypoint: bash
    args:
      - -c
      - |
        OLD_REVISION=$$(gcloud run services describe $${_SERVICE_NAME} \
          --region $${_REGION} \
          --platform managed \
          --format='value(status.latestReadyRevisionName)' 2>/dev/null)

        echo $$OLD_REVISION > /workspace/old_revision.txt
        echo "Ancienne révision : $$OLD_REVISION"
    id: "Sauvegarde Révision"
    waitFor: ["Pousser Image"]

  - name: "google/cloud-sdk"
    entrypoint: gcloud
    args: [
      "run","deploy","${_SERVICE_NAME}",
      "--image","europe-west1-docker.pkg.dev/$PROJECT_ID/hello-app/hello-app:latest",
      "--region","${_REGION}",
      "--platform","managed",
      "--allow-unauthenticated",
      "--set-env-vars","BUILD_ID=$BUILD_ID"
    ]
    id: "Déploiement Cloud Run"
    waitFor: ["Sauvegarde Révision"]

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: bash
    args:
      - -c
      - |
        SERVICE_NAME="$${_SERVICE_NAME}"
        REGION="$${_REGION}"
        OLD_REVISION=$$(cat /workspace/old_revision.txt)

        URL=$$(gcloud run services describe "$$SERVICE_NAME" --region "$$REGION" \
          --format='value(status.url)')

        echo "Smoke test: $${URL}/health"
        OK=0

        for i in 1 2 3; do
          STATUS=$$(curl -s -o /dev/null -w "%{http_code}" "$${URL}/health") || STATUS=0
          echo "Tentative $$i -> HTTP $$STATUS"
          if [ "$$STATUS" -ge 200 ] && [ "$$STATUS" -lt 300 ]; then OK=1; break; fi
          sleep $$((i * 3))
        done

        if [ "$$OK" -ne 1 ]; then
          echo "Smoke test KO"
          echo "Rollback vers $$OLD_REVISION"
          gcloud run services update-traffic "$$SERVICE_NAME" \
            --region "$$REGION" \
            --to-revisions "$$OLD_REVISION=100"
          exit 1
        fi

        echo "Smoke test OK"
    id: "Smoke Test & Rollback"
    waitFor: ["Déploiement Cloud Run"]

images:
  - "europe-west1-docker.pkg.dev/$PROJECT_ID/hello-app/hello-app:latest"

serviceAccount: "cloud-run-deployer@ci-cd-cloudrun.iam.gserviceaccount.com"

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: "E2_HIGHCPU_8"

substitutions:
  _SERVICE_NAME: "hello-app"
  _REGION: "europe-west1"
