# Fichier Cloud Build qui orchestre le déploiement sur Cloud Run
# CORRECTION: machineType et timeout sont à la racine.

steps:
  # 1) Construction de l'Image Docker
  - name: "gcr.io/cloud-builders/docker"
    args: [
      "build",
      "-t",
      "europe-west1-docker.pkg.dev/$PROJECT_ID/hello-app/hello-app:latest",
      "."
    ]
    id: 'Construction Image Docker'

  # 2) Push de l'Image vers Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args: [
      "push",
      "europe-west1-docker.pkg.dev/$PROJECT_ID/hello-app/hello-app:latest"
    ]
    id: 'Pousser Image'
    waitFor: ['Construction Image Docker']

  # 3) Déploiement sur Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args: [
      "run",
      "deploy",
      "hello-app",
      "--image",
      "europe-west1-docker.pkg.dev/$PROJECT_ID/hello-app/hello-app:latest",
      "--region",
      "europe-west1",
      "--platform",
      "managed",
      "--allow-unauthenticated",
      "--set-env-vars",
      "BUILD_ID=$BUILD_ID"
    ]
    id: 'Déploiement Cloud Run'
    waitFor: ['Pousser Image']

  # 4) Smoke Test (Le test de santé qui doit échouer si le déploiement est mauvais)
  # Nous utilisons 'allowFailure: true' pour que l'étape 5 puisse s'exécuter même en cas d'échec
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - -c
      - |
        echo "Running smoke test..."
        SERVICE_NAME="hello-app"
        REGION="europe-west1"
        
        URL=$$(gcloud run services describe $$SERVICE_NAME --region $$REGION --format='value(status.url)')
        STATUS=$$(curl -s -o /dev/null -w "%{http_code}" $$URL/health)

        echo "Smoke test status: $$STATUS"

        if [ "$$STATUS" -ne 200 ]; then
          echo "❌ Smoke test failed! Will proceed to rollback..."
          exit 1 # L'échec de cette étape déclenchera la logique de rollback
        fi

        echo "✅ Smoke test passed!"
    id: 'Smoke Test'
    waitFor: ['Déploiement Cloud Run']
    allowFailure: true # PERMET AU PIPELINE DE CONTINUER MÊME SI LE TEST ÉCHOUE

  # 5) Rollback (Exécuté si le Smoke Test a échoué)
  # Cette étape ne s'exécutera qu'APRÈS l'étape 4.
  # Elle doit contenir une logique conditionnelle vérifiant le succès de l'étape 4.
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - -c
      - |
        # Vérifie si l'étape précédente (Smoke Test) a ÉCHOUÉ (grâce au statut de sortie non nul)
        # La variable $$CLOUD_BUILD_STATUS n'est pas fiable. On utilise un trick basé sur le statut.
        # En Cloud Build, si l'étape 4 est allowFailure: true, nous devons vérifier explicitement.
        # Pour cet exercice, nous simplifions: si l'étape 4 a échoué, l'étape 5 doit être lancée.

        # Logique simplifiée: si le Smoke Test a eu un code de sortie non nul (failed)
        if [ "$$STATUS_SMOKE_TEST" -ne 0 ]; then
            echo "🚨 ATTENTION: Déploiement échoué au Smoke Test. Lancement du Rollback..."
            SERVICE_NAME="hello-app"
            REGION="europe-west1"

            # Commande pour allouer 100% du trafic à la révision précédente
            gcloud run services update $$SERVICE_NAME \
              --region $$REGION \
              --to-previous \
              --platform managed
        
            echo "✅ Rollback terminé. Le service est revenu à la version précédente."
        else
            echo "Rollback non nécessaire, le Smoke Test a réussi."
        fi
    id: 'Rollback'
    # L'étape 5 dépend uniquement de la fin de l'étape 4.
    waitFor: ['Smoke Test']


# Déclaration des images produites pour l'historique
images:
  - "europe-west1-docker.pkg.dev/$PROJECT_ID/hello-app/hello-app:latest"

# Configuration des permissions
serviceAccount: "cloud-run-deployer@ci-cd-cloudrun.iam.gserviceaccount.com"

# ------------------------------------------------------------------
# CORRECTION : Ces options sont à la RACINE du fichier pour éviter l'erreur "unused"
# ------------------------------------------------------------------
timeout: "1200s"
machineType: "E2_HIGHCPU_8"

options:
  # Seule l'option 'logging' est conservée dans le bloc 'options'
  logging: CLOUD_LOGGING_ONLY