steps:
  # 1) Install dependencies for testing
  - name: 'python:3.11-slim'
    entrypoint: 'bash'
    args:
    - -c
    - |
      echo "Installing dependencies..."
      pip install -r requirements.txt --verbose
      echo "Running tests..."
      pytest -vv
  # 1) Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'europe-west1-docker.pkg.dev/$PROJECT_ID/hello-app/hello-app:latest',
        '.'
      ]

  # 2) Push image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'europe-west1-docker.pkg.dev/$PROJECT_ID/hello-app/hello-app:latest'
      ]

  # 3) Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run',
        'deploy',
        'hello-app',
        '--image',
        'europe-west1-docker.pkg.dev/$PROJECT_ID/hello-app/hello-app:latest',
        '--region',
        'europe-west1',
        '--platform',
        'managed',
        '--allow-unauthenticated'
      ]

images:
  - 'europe-west1-docker.pkg.dev/$PROJECT_ID/hello-app/hello-app:latest'
serviceAccount: "cloud-run-deployer@ci-cd-cloudrun.iam.gserviceaccount.com"
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
timeout: "1200s"