timeout: "1200s"

steps:
  # Build
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "europe-west1-docker.pkg.dev/$PROJECT_ID/hello-app/hello-app:latest", "."]
    id: "Build"

  # Push
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "europe-west1-docker.pkg.dev/$PROJECT_ID/hello-app/hello-app:latest"]
    id: "Push"
    waitFor: ["Build"]

  # Sauvegarde de la dernière révision READY
  - name: "google/cloud-sdk"
    entrypoint: bash
    args:
      - -c
      - |
        SERVICE_NAME="hello-app"
        REGION="europe-west1"

        OLD_REVISION=$(gcloud run services describe "$SERVICE_NAME" \
          --platform managed \
          --region "$REGION" \
          --format='value(status.latestReadyRevisionName)' )

        echo "$OLD_REVISION" > /workspace/old_revision.txt
        echo "Ancienne révision : $OLD_REVISION"
    id: "SaveRevision"
    waitFor: ["Push"]

  # Déploiement
  - name: "google/cloud-sdk"
    entrypoint: gcloud
    args: [
      "run","deploy","hello-app",
      "--image","europe-west1-docker.pkg.dev/$PROJECT_ID/hello-app/hello-app:latest",
      "--region","europe-west1",
      "--platform","managed",
      "--allow-unauthenticated"
    ]
    id: "Deploy"
    waitFor: ["SaveRevision"]

  # Smoke Test + Rollback
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: bash
    args:
      - -c
      - |
        SERVICE_NAME="hello-app"
        REGION="europe-west1"

        OLD_REVISION=$(cat /workspace/old_revision.txt)

        URL=$(gcloud run services describe "$SERVICE_NAME" \
          --region "$REGION" \
          --format="value(status.url)")

        echo "Smoke test: $URL/health"

        OK=0
        for i in 1 2 3; do
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" "$URL/health")
          echo "Tentative $i -> HTTP $STATUS"
          if [ "$STATUS" -ge 200 ] && [ "$STATUS" -lt 300 ]; then OK=1; break; fi
          sleep $((i*3))
        done

        if [ "$OK" -ne 1 ]; then
          echo "Smoke test KO"

          if [ -n "$OLD_REVISION" ]; then
            echo "Rollback vers $OLD_REVISION"

            gcloud run services update-traffic "$SERVICE_NAME" \
              --region "$REGION" \
              --to-revisions "$OLD_REVISION=100"
          else
            echo "Aucune révision précédente trouvée !"
          fi
          exit 1
        fi

        echo "Smoke test OK"
    id: "SmokeTest"
    waitFor: ["Deploy"]

images:
  - "europe-west1-docker.pkg.dev/$PROJECT_ID/hello-app/hello-app:latest"

serviceAccount: "cloud-run-deployer@ci-cd-cloudrun.iam.gserviceaccount.com"
options:
  logging: CLOUD_LOGGING_ONLY
